// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Nodechild_process from "node:child_process";

let onProcessData = (function(stream, cb) { stream.on("data", function(d) { cb(String(d)); }); });

let onProcessClose = (function(proc, cb) { proc.on("close", cb); });

let defaultConfig_sources = [
  "src",
  "lib",
  "examples"
];

let defaultConfig_dependencies = [];

let defaultConfig = {
  language: "affinescript",
  name: "unknown",
  suffix: ".as.js",
  sources: defaultConfig_sources,
  inSource: true,
  moduleFormat: "esmodule",
  configPath: "",
  dependencies: defaultConfig_dependencies
};

function stripAnsi(s) {
  return s.replace(/\x1b\[[0-9;]*m/g, "");
}

function parseDiagnostics(output) {
  let lines = output.split("\n");
  let diagnostics = [];
  let i = 0;
  while (i < lines.length) {
    let line = lines[i];
    let clean = stripAnsi(line);
    let ocamlMatch = ((function(s) {
        var m = s.match(/File "([^"]+)", line (\d+), characters (\d+)-(\d+)/);
        if (!m) return undefined;
        return [m[1], parseInt(m[2], 10), parseInt(m[3], 10), parseInt(m[4], 10)];
      })(clean));
    if (ocamlMatch !== undefined) {
      let lineNum = ocamlMatch[1];
      let sev = "error";
      let msgLines = [];
      let j = i + 1 | 0;
      let done = false;
      while (j < lines.length && !done) {
        let msgLine = stripAnsi(lines[j]);
        if (msgLine.startsWith("File ") || msgLine.trim().length === 0 && msgLines.length !== 0) {
          done = true;
        } else {
          if (msgLine.includes("Warning")) {
            sev = "warning";
          }
          let trimmed = msgLine.trim();
          if (trimmed.length > 0) {
            let cleaned = trimmed.replace(/^Error:\s*/, "").replace(/^Warning \d+:\s*/, "");
            msgLines.push(cleaned);
          }
          j = j + 1 | 0;
        }
      };
      diagnostics.push({
        file: ocamlMatch[0],
        line: lineNum,
        column: ocamlMatch[2],
        endLine: lineNum,
        endColumn: ocamlMatch[3],
        severity: sev,
        message: msgLines.join("\n"),
        language: "affinescript"
      });
      i = j;
    } else {
      let structMatch = ((function(s) {
            var m = s.match(/\[(Error|Warning|Info)\]\s+(.+?):(\d+):(\d+)/);
            if (!m) return undefined;
            return [m[1].toLowerCase(), m[2], parseInt(m[3], 10), parseInt(m[4], 10)];
          })(clean));
      if (structMatch !== undefined) {
        let col = structMatch[3];
        let lineNum$1 = structMatch[2];
        let sev$1;
        switch (structMatch[0]) {
          case "info" :
            sev$1 = "info";
            break;
          case "warning" :
            sev$1 = "warning";
            break;
          default:
            sev$1 = "error";
        }
        let m = clean.split(" - ")[1];
        let msg = m !== undefined ? m : clean;
        diagnostics.push({
          file: structMatch[1],
          line: lineNum$1,
          column: col,
          endLine: lineNum$1,
          endColumn: col,
          severity: sev$1,
          message: msg,
          language: "affinescript"
        });
        i = i + 1 | 0;
      } else {
        i = i + 1 | 0;
      }
    }
  };
  return diagnostics;
}

function detect(root) {
  let opamPath = Nodepath.join(root, "affinescript.opam");
  let buildOpamPath = Nodepath.join(root, ".build", "affinescript.opam");
  let dunePath = Nodepath.join(root, "dune-project");
  if (Nodefs.existsSync(opamPath)) {
    return opamPath;
  }
  if (Nodefs.existsSync(buildOpamPath)) {
    return buildOpamPath;
  }
  if (!Nodefs.existsSync(dunePath)) {
    return;
  }
  try {
    let content = Nodefs.readFileSync(dunePath, "utf-8");
    if (content.includes("affinescript")) {
      return dunePath;
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function readConfig(root) {
  let opamPath = Nodepath.join(root, "affinescript.opam");
  let buildOpamPath = Nodepath.join(root, ".build", "affinescript.opam");
  let configPath = Nodefs.existsSync(opamPath) ? opamPath : (
      Nodefs.existsSync(buildOpamPath) ? buildOpamPath : ""
    );
  if (configPath === "") {
    return defaultConfig;
  }
  try {
    Nodefs.readFileSync(configPath, "utf-8");
    let name = ((function(c) {
          var m = c.match(/name:\s*"([^"]+)"/);
          return m ? m[1] : "affinescript";
        })(content));
    let sources = [];
    if (Nodefs.existsSync(Nodepath.join(root, "lib"))) {
      sources.push("lib");
    }
    if (Nodefs.existsSync(Nodepath.join(root, "bin"))) {
      sources.push("bin");
    }
    if (Nodefs.existsSync(Nodepath.join(root, "examples"))) {
      sources.push("examples");
    }
    if (Nodefs.existsSync(Nodepath.join(root, "src"))) {
      sources.push("src");
    }
    if (sources.length === 0) {
      sources.push("lib");
    }
    return {
      language: "affinescript",
      name: name,
      suffix: ".as.js",
      sources: sources,
      inSource: true,
      moduleFormat: "esmodule",
      configPath: configPath,
      dependencies: []
    };
  } catch (exn) {
    return defaultConfig;
  }
}

function getOutputPath(_config, asFile) {
  return asFile + ".js";
}

function build(root, _config) {
  return new Promise((resolve, _reject) => {
    let startTime = performance.now();
    let outputBuf = {
      contents: ""
    };
    let errorBuf = {
      contents: ""
    };
    let match = Nodefs.existsSync(Nodepath.join(root, "dune-project")) ? [
        "dune",
        [
          "exec",
          "affinescript",
          "--",
          "build"
        ]
      ] : [
        "affinescript",
        ["build"]
      ];
    let proc = Nodechild_process.spawn(match[0], match[1], {
      cwd: root,
      shell: true
    });
    onProcessData(proc.stdout, chunk => {
      outputBuf.contents = outputBuf.contents + chunk;
    });
    onProcessData(proc.stderr, chunk => {
      errorBuf.contents = errorBuf.contents + chunk;
    });
    onProcessClose(proc, code => {
      let allOutput = outputBuf.contents + errorBuf.contents;
      let diagnostics = parseDiagnostics(allOutput);
      let duration = performance.now() - startTime;
      resolve({
        success: code === 0,
        diagnostics: diagnostics,
        changedFiles: [],
        durationMs: duration
      });
    });
  });
}

function watch(root, _config) {
  let match = Nodefs.existsSync(Nodepath.join(root, "dune-project")) ? [
      "dune",
      [
        "build",
        "--watch"
      ]
    ] : [
      "affinescript",
      ["build"]
    ];
  let proc = Nodechild_process.spawn(match[0], match[1], {
    cwd: root,
    shell: true
  });
  return {
    stop: () => {
      proc.kill();
    },
    stopped: false
  };
}

function resolveImport(_source, _importer, _config) {
  
}

function make() {
  return {
    id: "affinescript",
    displayName: "AffineScript",
    extensions: [".as"],
    detect: detect,
    readConfig: readConfig,
    defaultConfig: defaultConfig,
    getOutputPath: getOutputPath,
    build: build,
    watch: watch,
    parseDiagnostics: parseDiagnostics,
    resolveImport: resolveImport,
    excludePackages: [],
    artifactIgnorePatterns: [
      "**/_build/**",
      "**/.merlin",
      "**/*.cmi",
      "**/*.cmo",
      "**/*.cmx",
      "**/*.cmt",
      "**/*.cmti",
      "**/*.o",
      "**/*.a",
      "**/*.as.wasm",
      "**/*.as.jl"
    ]
  };
}

export {
  onProcessData,
  onProcessClose,
  defaultConfig,
  stripAnsi,
  parseDiagnostics,
  detect,
  readConfig,
  getOutputPath,
  build,
  watch,
  resolveImport,
  make,
}
/* node:fs Not a pure module */
