// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let defaultEndpoint = "http://localhost:7077/mcp/ssg";

function make(endpointOpt) {
  let endpoint = endpointOpt !== undefined ? endpointOpt : defaultEndpoint;
  return {
    state: "Disconnected",
    endpoint: endpoint,
    events: []
  };
}

async function probe(bridge) {
  bridge.state = "Connecting";
  try {
    let resp = await fetch(bridge.endpoint + "/health");
    if (resp.ok) {
      let body = await resp.text();
      bridge.state = {
        TAG: "Connected",
        _0: body
      };
      return true;
    }
    bridge.state = {
      TAG: "Failed",
      _0: "BoJ not healthy: " + resp.status.toString()
    };
    return false;
  } catch (exn) {
    bridge.state = {
      TAG: "Failed",
      _0: "BoJ unreachable at " + bridge.endpoint
    };
    return false;
  }
}

function isConnected(bridge) {
  let match = bridge.state;
  if (typeof match !== "object") {
    return false;
  } else {
    return match.TAG === "Connected";
  }
}

async function requestBuild(bridge, request) {
  if (!isConnected(bridge)) {
    return;
  }
  try {
    let bodyStr = Stdlib_Option.getOr(JSON.stringify({
      jsonrpc: "2.0",
      method: "tools/call",
      params: {
        name: "ssg_build",
        arguments: {
          project_root: request.projectRoot,
          targets: request.targets,
          incremental: request.incremental,
          changed_files: request.changedFiles,
          compiler_flags: request.compilerFlags
        }
      }
    }), "");
    let resp = await fetch(bridge.endpoint, {
      method: "POST",
      headers: {
        "content-type": "application/json"
      },
      body: bodyStr
    });
    if (!resp.ok) {
      return;
    }
    let json = await resp.json();
    bridge.events.push({
      project: request.projectRoot,
      timestamp: Date.now(),
      success: json.success,
      fileCount: request.changedFiles.length,
      diagnosticCount: json.diagnosticCount,
      durationMs: json.durationMs,
      cacheHitRate: (json.diagnosticCount + json.cacheHits | 0) > 0 ? json.cacheHits / (json.diagnosticCount + json.cacheHits | 0) : 0.0
    });
    return json;
  } catch (exn) {
    return;
  }
}

function recentEvents(bridge, limitOpt) {
  let limit = limitOpt !== undefined ? limitOpt : 20;
  let len = bridge.events.length;
  if (len <= limit) {
    return bridge.events;
  } else {
    return bridge.events.slice(len - limit | 0, len);
  }
}

function disconnect(bridge) {
  bridge.state = "Disconnected";
}

export {
  defaultEndpoint,
  make,
  probe,
  isConnected,
  requestBuild,
  recentEvents,
  disconnect,
}
/* No side effect */
