// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function detectLanguage(adapters, root) {
  let result;
  let i = 0;
  while (i < adapters.length && Stdlib_Option.isNone(result)) {
    let adapter = adapters[i];
    let configPath = adapter.detect(root);
    if (configPath !== undefined) {
      result = [
        adapter,
        configPath
      ];
    }
    i = i + 1 | 0;
  };
  return result;
}

function detectAllLanguages(adapters, root) {
  return Stdlib_Array.filterMap(adapters, adapter => {
    let configPath = adapter.detect(root);
    if (configPath !== undefined) {
      return [
        adapter,
        configPath
      ];
    }
  });
}

function mergeExcludePackages(adapters) {
  let seen = {};
  let result = [];
  adapters.forEach(adapter => {
    adapter.excludePackages.forEach(pkg => {
      if (!Stdlib_Option.getOr(seen[pkg], false)) {
        seen[pkg] = true;
        result.push(pkg);
        return;
      }
    });
  });
  return result;
}

function mergeArtifactPatterns(adapters) {
  let seen = {};
  let result = [];
  adapters.forEach(adapter => {
    adapter.artifactIgnorePatterns.forEach(pat => {
      if (!Stdlib_Option.getOr(seen[pat], false)) {
        seen[pat] = true;
        result.push(pat);
        return;
      }
    });
  });
  return result;
}

export {
  detectLanguage,
  detectAllLanguages,
  mergeExcludePackages,
  mergeArtifactPatterns,
}
/* No side effect */
