// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";

let defaultRescriptConfig_packageSpec = {
  moduleFormat: "esmodule",
  inSource: true
};

let defaultRescriptConfig_sources = ["src"];

let defaultRescriptConfig_dependencies = ["@rescript/core"];

let defaultRescriptConfig = {
  name: "unknown",
  suffix: ".res.js",
  packageSpec: defaultRescriptConfig_packageSpec,
  sources: defaultRescriptConfig_sources,
  dependencies: defaultRescriptConfig_dependencies,
  configPath: ""
};

let parseSources = (function(sources) {
    if (!sources) return ["src"];
    if (typeof sources === "string") return [sources];
    if (Array.isArray(sources)) {
      return sources.map(function(s) {
        if (typeof s === "string") return s;
        if (s && s.dir) return s.dir;
        return "src";
      });
    }
    if (sources.dir) return [sources.dir];
    return ["src"];
  });

let parsePackageSpec = (function(specs) {
    var defaultSpec = { moduleFormat: "esmodule", inSource: true };
    if (!specs) return defaultSpec;
    // Single string: "esmodule" or "commonjs"
    if (typeof specs === "string") return { moduleFormat: specs, inSource: true };
    // Array of specs — take the first
    var spec = Array.isArray(specs) ? specs[0] : specs;
    if (!spec) return defaultSpec;
    if (typeof spec === "string") return { moduleFormat: spec, inSource: true };
    var fmt = spec.module || spec["module"] || "esmodule";
    // Normalise legacy format names
    if (fmt === "es6" || fmt === "es6-global") fmt = "esmodule";
    var inSrc = spec["in-source"];
    return {
      moduleFormat: fmt,
      inSource: inSrc !== undefined ? !!inSrc : true
    };
  });

let parseDeps = (function(deps) {
    if (!deps) return [];
    if (Array.isArray(deps)) return deps.filter(function(d) { return typeof d === "string"; });
    return [];
  });

function read(projectRoot) {
  let rescriptJsonPath = Nodepath.join(projectRoot, "rescript.json");
  let bsconfigPath = Nodepath.join(projectRoot, "bsconfig.json");
  let configPath = Nodefs.existsSync(rescriptJsonPath) ? rescriptJsonPath : (
      Nodefs.existsSync(bsconfigPath) ? bsconfigPath : undefined
    );
  if (configPath === undefined) {
    return defaultRescriptConfig;
  }
  try {
    let content = Nodefs.readFileSync(configPath, "utf-8");
    let json = JSON.parse(content);
    let obj = Stdlib_JSON.Classify.classify(json);
    let exit = 0;
    if (typeof obj !== "object") {
      exit = 1;
    } else {
      if (obj.TAG === "Object") {
        let obj$1 = obj._0;
        let v = obj$1["name"];
        let name;
        if (v !== undefined) {
          let s = Stdlib_JSON.Classify.classify(v);
          name = typeof s !== "object" || s.TAG !== "String" ? "unknown" : s._0;
        } else {
          name = "unknown";
        }
        let v$1 = obj$1["suffix"];
        let suffix;
        if (v$1 !== undefined) {
          let s$1 = Stdlib_JSON.Classify.classify(v$1);
          suffix = typeof s$1 !== "object" || s$1.TAG !== "String" ? ".res.js" : s$1._0;
        } else {
          suffix = ".res.js";
        }
        let v$2 = obj$1["package-specs"];
        let packageSpec = v$2 !== undefined ? parsePackageSpec(v$2) : ({
            moduleFormat: "esmodule",
            inSource: true
          });
        let v$3 = obj$1["sources"];
        let sources = v$3 !== undefined ? parseSources(v$3) : ["src"];
        let v$4 = obj$1["dependencies"];
        let dependencies;
        if (v$4 !== undefined) {
          dependencies = parseDeps(v$4);
        } else {
          let v$5 = obj$1["bs-dependencies"];
          dependencies = v$5 !== undefined ? parseDeps(v$5) : [];
        }
        return {
          name: name,
          suffix: suffix,
          packageSpec: packageSpec,
          sources: sources,
          dependencies: dependencies,
          configPath: configPath
        };
      }
      exit = 1;
    }
    if (exit === 1) {
      return {
        name: "unknown",
        suffix: ".res.js",
        packageSpec: {
          moduleFormat: "esmodule",
          inSource: true
        },
        sources: defaultRescriptConfig_sources,
        dependencies: defaultRescriptConfig_dependencies,
        configPath: configPath
      };
    }
  } catch (exn) {
    return defaultRescriptConfig;
  }
}

function getOutputPath(config, resFile) {
  if (config.packageSpec.inSource) {
    return resFile + config.suffix.replace(".res", "");
  }
  let other = config.packageSpec.moduleFormat;
  let subdir;
  switch (other) {
    case "commonjs" :
      subdir = "js";
      break;
    case "esmodule" :
      subdir = "es6";
      break;
    default:
      subdir = other;
  }
  return "lib/" + subdir + "/" + resFile + config.suffix.replace(".res", "");
}

export {
  defaultRescriptConfig,
  parseSources,
  parsePackageSpec,
  parseDeps,
  read,
  getOutputPath,
}
/* node:fs Not a pure module */
