// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as RescriptConfig from "./RescriptConfig.res.js";
import * as RescriptCompiler from "./RescriptCompiler.res.js";
import * as VitePluginRescript from "./VitePluginRescript.res.js";

function convertSeverity(sev) {
  if (sev === "Error") {
    return "error";
  } else {
    return "warning";
  }
}

function convertDiagnostic(d) {
  return {
    file: d.file,
    line: d.line,
    column: d.column,
    endLine: d.endLine,
    endColumn: d.endColumn,
    severity: convertSeverity(d.severity),
    message: d.message,
    language: "rescript"
  };
}

function convertConfig(c) {
  return {
    language: "rescript",
    name: c.name,
    suffix: c.suffix,
    sources: c.sources,
    inSource: c.packageSpec.inSource,
    moduleFormat: c.packageSpec.moduleFormat,
    configPath: c.configPath,
    dependencies: c.dependencies
  };
}

function make() {
  return {
    id: "rescript",
    displayName: "ReScript",
    extensions: [
      ".res",
      ".resi"
    ],
    detect: root => {
      let rescriptJson = Nodepath.join(root, "rescript.json");
      let bsconfig = Nodepath.join(root, "bsconfig.json");
      if (Nodefs.existsSync(rescriptJson)) {
        return rescriptJson;
      } else if (Nodefs.existsSync(bsconfig)) {
        return bsconfig;
      } else {
        return;
      }
    },
    readConfig: root => convertConfig(RescriptConfig.read(root)),
    defaultConfig: convertConfig(RescriptConfig.defaultRescriptConfig),
    getOutputPath: (config, resFile) => {
      let rescriptConfig_name = config.name;
      let rescriptConfig_suffix = config.suffix;
      let rescriptConfig_packageSpec = {
        moduleFormat: config.moduleFormat,
        inSource: config.inSource
      };
      let rescriptConfig_sources = config.sources;
      let rescriptConfig_dependencies = config.dependencies;
      let rescriptConfig_configPath = config.configPath;
      let rescriptConfig = {
        name: rescriptConfig_name,
        suffix: rescriptConfig_suffix,
        packageSpec: rescriptConfig_packageSpec,
        sources: rescriptConfig_sources,
        dependencies: rescriptConfig_dependencies,
        configPath: rescriptConfig_configPath
      };
      return RescriptConfig.getOutputPath(rescriptConfig, resFile);
    },
    build: (root, _config) => {
      let compilerConfig = RescriptCompiler.defaultConfig(root);
      return RescriptCompiler.build(compilerConfig).then(result => ({
        success: result.success,
        diagnostics: result.diagnostics.map(convertDiagnostic),
        changedFiles: result.changedFiles,
        durationMs: result.durationMs
      }));
    },
    watch: (root, _config) => {
      let compilerConfig = RescriptCompiler.defaultConfig(root);
      let handle = RescriptCompiler.watch(compilerConfig);
      return {
        stop: () => RescriptCompiler.stop(handle),
        stopped: false
      };
    },
    parseDiagnostics: output => RescriptCompiler.parseDiagnostics(output).map(convertDiagnostic),
    resolveImport: (source, importer, config) => VitePluginRescript.tryPascalCaseResolve(source, importer, config.suffix),
    excludePackages: [
      "@rescript/core",
      "@rescript/runtime",
      "@rescript/react",
      "rescript"
    ],
    artifactIgnorePatterns: [
      "**/*.ast",
      "**/*.cmj",
      "**/*.cmi",
      "**/*.cmt",
      "**/lib/bs/**",
      "**/lib/es6/**",
      "**/lib/js/**",
      "**/lib/ocaml/**",
      "**/.merlin",
      "**/.bsb.lock"
    ]
  };
}

export {
  convertSeverity,
  convertDiagnostic,
  convertConfig,
  make,
}
/* node:fs Not a pure module */
