// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Nodechild_process from "node:child_process";

function defaultConfig(cwd) {
  return {
    cwd: cwd,
    rescriptBin: undefined,
    useDeno: false,
    useRewatch: false,
    compilerFlags: [],
    onDiagnostic: undefined,
    onFileChanged: undefined
  };
}

let onProcessData = (function(stream, cb) { stream.on("data", function(d) { cb(String(d)); }); });

let onProcessClose = (function(proc, cb) { proc.on("close", cb); });

function stripAnsi(s) {
  return s.replace(/\x1b\[[0-9;]*m/g, "");
}

let matchFileLoc = (function(s) {
    var m = s.match(/^\s+(.+\.resi?):(\d+):(\d+)(?:-(\d+))?/);
    if (!m) return undefined;
    return [m[1], parseInt(m[2], 10), parseInt(m[3], 10), m[4] ? parseInt(m[4], 10) : parseInt(m[3], 10)];
  });

let matchCompiledFile = (function(s) {
    var m = s.match(/(?:Building|Compiling)\s+(.+\.res)/i);
    return m ? m[1] : undefined;
  });

function parseDiagnostics(output) {
  let lines = output.split("\n");
  let diagnostics = [];
  let i = 0;
  while (i < lines.length) {
    let line = lines[i];
    let clean = stripAnsi(line);
    let match = matchFileLoc(clean);
    if (match !== undefined) {
      let lineNum = match[1];
      let sev;
      if (i > 0) {
        let prev = lines[i - 1 | 0];
        sev = prev.includes("bug for you") || prev.includes("Error") ? "Error" : "Warning";
      } else {
        sev = "Error";
      }
      let msgLines = [];
      let j = i + 1 | 0;
      let done = false;
      while (j < lines.length && !done) {
        let msgLine = lines[j];
        let msgClean = stripAnsi(msgLine);
        if (Stdlib_Option.isSome(matchFileLoc(msgClean)) || msgClean.includes("We've found a bug") || msgClean.includes("Warning number")) {
          done = true;
        } else {
          if (msgClean.trim().length > 0) {
            msgLines.push(msgClean.trim());
          }
          j = j + 1 | 0;
        }
      };
      diagnostics.push({
        file: match[0],
        line: lineNum,
        column: match[2],
        endLine: lineNum,
        endColumn: match[3],
        severity: sev,
        message: msgLines.join("\n")
      });
      i = j;
    } else {
      i = i + 1 | 0;
    }
  };
  return diagnostics;
}

function parseChangedFiles(output) {
  let lines = output.split("\n");
  let changed = [];
  lines.forEach(line => {
    let clean = stripAnsi(line);
    let file = matchCompiledFile(clean);
    if (file === undefined) {
      return;
    }
    let jsFile = file + ".js";
    changed.push(jsFile);
  });
  return changed;
}

function buildCommand(config, watchMode) {
  if (config.useRewatch) {
    let args = watchMode ? [
        "rewatch",
        "watch"
      ].concat(config.compilerFlags) : [
        "rewatch",
        "build"
      ].concat(config.compilerFlags);
    return [
      "npx",
      args
    ];
  }
  if (config.useDeno) {
    let watchArg = watchMode ? ["-w"] : [];
    return [
      "deno",
      [
        "run",
        "-A",
        "npm:rescript",
        "build"
      ].concat(watchArg).concat(config.compilerFlags)
    ];
  }
  let bin = Stdlib_Option.getOr(config.rescriptBin, "npx");
  let baseArgs;
  if (bin === "npx") {
    let watchArg$1 = watchMode ? ["-w"] : [];
    baseArgs = [
      "rescript",
      "build"
    ].concat(watchArg$1);
  } else {
    let watchArg$2 = watchMode ? ["-w"] : [];
    baseArgs = ["build"].concat(watchArg$2);
  }
  return [
    bin,
    baseArgs.concat(config.compilerFlags)
  ];
}

function build(config) {
  return new Promise((resolve, _reject) => {
    let startTime = performance.now();
    let match = buildCommand(config, false);
    let outputBuf = {
      contents: ""
    };
    let errorBuf = {
      contents: ""
    };
    let proc = Nodechild_process.spawn(match[0], match[1], {
      cwd: config.cwd,
      shell: true,
      env: (Object.assign({}, process.env, { NINJA_ANSI_FORCED: "1" }))
    });
    onProcessData(proc.stdout, chunk => {
      outputBuf.contents = outputBuf.contents + chunk;
    });
    onProcessData(proc.stderr, chunk => {
      errorBuf.contents = errorBuf.contents + chunk;
    });
    onProcessClose(proc, code => {
      let allOutput = outputBuf.contents + errorBuf.contents;
      let diagnostics = parseDiagnostics(allOutput);
      let changedFiles = parseChangedFiles(allOutput);
      let duration = performance.now() - startTime;
      let cb = config.onDiagnostic;
      if (cb !== undefined) {
        diagnostics.forEach(cb);
      }
      let cb$1 = config.onFileChanged;
      if (cb$1 !== undefined) {
        changedFiles.forEach(cb$1);
      }
      resolve({
        success: code === 0,
        diagnostics: diagnostics,
        changedFiles: changedFiles,
        durationMs: duration
      });
    });
  });
}

function watch(config) {
  let match = buildCommand(config, true);
  let proc = Nodechild_process.spawn(match[0], match[1], {
    cwd: config.cwd,
    shell: true,
    env: (Object.assign({}, process.env, { NINJA_ANSI_FORCED: "1" }))
  });
  onProcessData(proc.stderr, chunk => {
    let diagnostics = parseDiagnostics(chunk);
    let cb = config.onDiagnostic;
    if (cb !== undefined) {
      diagnostics.forEach(cb);
      return;
    }
  });
  onProcessData(proc.stdout, chunk => {
    let changed = parseChangedFiles(chunk);
    let cb = config.onFileChanged;
    if (cb !== undefined) {
      changed.forEach(cb);
      return;
    }
  });
  return {
    process: proc,
    stopped: false
  };
}

function stop(handle) {
  if (!handle.stopped) {
    handle.process.kill();
    handle.stopped = true;
    return;
  }
}

export {
  defaultConfig,
  onProcessData,
  onProcessClose,
  stripAnsi,
  matchFileLoc,
  matchCompiledFile,
  parseDiagnostics,
  parseChangedFiles,
  buildCommand,
  build,
  watch,
  stop,
}
/* node:child_process Not a pure module */
