// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BojBridge from "./BojBridge.res.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as RescriptCompiler from "./RescriptCompiler.res.js";

function log(level, prefix, msg) {
  if (level !== "silent") {
    console.log(`[rescript-vite] ` + prefix + ` ` + msg);
    return;
  }
}

function logInfo(level, msg) {
  log(level, "\x1b[36mℹ\x1b[0m", msg);
}

function logOk(level, msg) {
  log(level, "\x1b[32m✓\x1b[0m", msg);
}

function logWarn(level, msg) {
  log(level, "\x1b[33m⚠\x1b[0m", msg);
}

function logErr(level, msg) {
  log(level, "\x1b[31m✗\x1b[0m", msg);
}

function isDeno() {
  return (typeof Deno !== "undefined");
}

function sendOverlayError(server, diagnostic) {
  server.ws.send({
    type: "error",
    err: {
      message: diagnostic.message,
      stack: "",
      id: diagnostic.file,
      frame: diagnostic.file + `:` + diagnostic.line.toString() + `:` + diagnostic.column.toString(),
      plugin: "rescript-vite",
      loc: {
        file: diagnostic.file,
        line: diagnostic.line,
        column: diagnostic.column
      }
    }
  });
}

function clearOverlay(server) {
  server.ws.send({
    type: "update",
    updates: []
  });
}

function make(optionsOpt) {
  let options = optionsOpt !== undefined ? Primitive_option.valFromOption(optionsOpt) : undefined;
  let opts = Stdlib_Option.getOr(options, {
    boj: undefined,
    bojEndpoint: undefined,
    useDeno: undefined,
    rescriptBin: undefined,
    compilerFlags: undefined,
    logLevel: undefined
  });
  let logLevel = Stdlib_Option.getOr(opts.logLevel, "info");
  let useDeno = Stdlib_Option.getOr(opts.useDeno, isDeno());
  let state = {
    config: undefined,
    watchHandle: undefined,
    bojBridge: undefined,
    pendingHmrFiles: [],
    lastBuildSuccess: true,
    diagnostics: []
  };
  return {
    name: "rescript-vite",
    enforce: "pre",
    configResolved: resolvedConfig => {
      state.config = resolvedConfig;
      log(logLevel, "\x1b[36mℹ\x1b[0m", `Project root: ` + resolvedConfig.root);
      log(logLevel, "\x1b[36mℹ\x1b[0m", `Mode: ` + resolvedConfig.command + ` (` + resolvedConfig.mode + `)`);
    },
    buildStart: async () => {
      let c = state.config;
      let root = c !== undefined ? c.root : ".";
      let wantBoj = Stdlib_Option.getOr(opts.boj, false);
      if (wantBoj) {
        let bridge = BojBridge.make(Stdlib_Option.getOr(opts.bojEndpoint, BojBridge.defaultEndpoint));
        let connected = await BojBridge.probe(bridge);
        if (connected) {
          state.bojBridge = bridge;
          log(logLevel, "\x1b[32m✓\x1b[0m", "BoJ ssg-mcp connected — build orchestration delegated");
        } else {
          log(logLevel, "\x1b[33m⚠\x1b[0m", "BoJ not available — falling back to direct compiler");
        }
      }
      let init = RescriptCompiler.defaultConfig(root);
      let compilerConfig_cwd = init.cwd;
      let compilerConfig_rescriptBin = opts.rescriptBin;
      let compilerConfig_compilerFlags = Stdlib_Option.getOr(opts.compilerFlags, []);
      let compilerConfig_onDiagnostic = d => {
        state.diagnostics.push(d);
        let match = d.severity;
        let sevStr;
        sevStr = match === "Error" ? "error" : "warning";
        if (sevStr === "error") {
          log(logLevel, "\x1b[31m✗\x1b[0m", d.file + `:` + d.line.toString() + ` — ` + d.message);
          state.lastBuildSuccess = false;
          return;
        } else if (logLevel === "verbose") {
          return log(logLevel, "\x1b[33m⚠\x1b[0m", d.file + `:` + d.line.toString() + ` — ` + d.message);
        } else {
          return;
        }
      };
      let compilerConfig_onFileChanged = file => {
        state.pendingHmrFiles.push(file);
      };
      let compilerConfig = {
        cwd: compilerConfig_cwd,
        rescriptBin: compilerConfig_rescriptBin,
        useDeno: useDeno,
        compilerFlags: compilerConfig_compilerFlags,
        onDiagnostic: compilerConfig_onDiagnostic,
        onFileChanged: compilerConfig_onFileChanged
      };
      let c$1 = state.config;
      let config = c$1 !== undefined ? c$1 : ({
          root: ".",
          command: "build",
          mode: "production"
        });
      if (config.command === "serve") {
        log(logLevel, "\x1b[36mℹ\x1b[0m", "Starting ReScript compiler in watch mode...");
        let handle = RescriptCompiler.watch(compilerConfig);
        state.watchHandle = handle;
        return log(logLevel, "\x1b[32m✓\x1b[0m", "ReScript watch mode active");
      }
      log(logLevel, "\x1b[36mℹ\x1b[0m", "Running ReScript build...");
      let bridge$1 = state.bojBridge;
      if (bridge$1 !== undefined) {
        let result = await BojBridge.requestBuild(bridge$1, {
          projectRoot: root,
          targets: ["client"],
          incremental: false,
          changedFiles: [],
          compilerFlags: Stdlib_Option.getOr(opts.compilerFlags, [])
        });
        if (result !== undefined) {
          state.lastBuildSuccess = result.success;
          if (result.success) {
            return log(logLevel, "\x1b[32m✓\x1b[0m", `BoJ build complete (` + result.durationMs.toString() + `ms, ` + result.cacheHits.toString() + ` cache hits)`);
          } else {
            return log(logLevel, "\x1b[31m✗\x1b[0m", `BoJ build failed (` + result.diagnosticCount.toString() + ` errors)`);
          }
        }
        log(logLevel, "\x1b[33m⚠\x1b[0m", "BoJ build request failed — falling back to direct compiler");
        let result$1 = await RescriptCompiler.build(compilerConfig);
        state.lastBuildSuccess = result$1.success;
        if (result$1.success) {
          return log(logLevel, "\x1b[32m✓\x1b[0m", `Build complete (` + result$1.durationMs.toString() + `ms)`);
        } else {
          return log(logLevel, "\x1b[31m✗\x1b[0m", `Build failed (` + result$1.diagnostics.length.toString() + ` errors)`);
        }
      }
      let result$2 = await RescriptCompiler.build(compilerConfig);
      state.lastBuildSuccess = result$2.success;
      if (result$2.success) {
        return log(logLevel, "\x1b[32m✓\x1b[0m", `Build complete (` + result$2.durationMs.toString() + `ms)`);
      } else {
        return log(logLevel, "\x1b[31m✗\x1b[0m", `Build failed (` + result$2.diagnostics.length.toString() + ` errors)`);
      }
    },
    handleHotUpdate: ctx => {
      let file = ctx.file;
      if (!(file.endsWith(".res") || file.endsWith(".resi"))) {
        return;
      }
      log(logLevel, "\x1b[36mℹ\x1b[0m", `File changed: ` + file);
      let jsFile = file + ".js";
      let modules = ctx.server.moduleGraph.getModulesByFile(jsFile);
      if (modules !== undefined && modules.length !== 0) {
        if (state.lastBuildSuccess) {
          clearOverlay(ctx.server);
        }
        let errors = state.diagnostics.filter(d => d.severity === "Error");
        if (errors.length !== 0) {
          let err = errors[0];
          if (err !== undefined) {
            sendOverlayError(ctx.server, err);
          }
        }
        state.diagnostics = [];
        return modules;
      }
      log(logLevel, "\x1b[36mℹ\x1b[0m", `Full reload for ` + file + ` (not in module graph)`);
    },
    buildEnd: () => {
      let errorCount = state.diagnostics.filter(d => d.severity === "Error").length;
      let warnCount = state.diagnostics.filter(d => d.severity === "Warning").length;
      if (errorCount > 0) {
        return log(logLevel, "\x1b[31m✗\x1b[0m", errorCount.toString() + ` errors, ` + warnCount.toString() + ` warnings`);
      } else if (warnCount > 0) {
        return log(logLevel, "\x1b[33m⚠\x1b[0m", warnCount.toString() + ` warnings`);
      } else {
        return log(logLevel, "\x1b[32m✓\x1b[0m", "No issues");
      }
    },
    closeBundle: () => {
      let handle = state.watchHandle;
      if (handle !== undefined) {
        RescriptCompiler.stop(handle);
        log(logLevel, "\x1b[36mℹ\x1b[0m", "ReScript watch mode stopped");
      }
      let bridge = state.bojBridge;
      if (bridge !== undefined) {
        BojBridge.disconnect(bridge);
        return log(logLevel, "\x1b[36mℹ\x1b[0m", "BoJ disconnected");
      }
    }
  };
}

let $$default = make(Primitive_option.some(undefined));

export {
  log,
  logInfo,
  logOk,
  logWarn,
  logErr,
  isDeno,
  sendOverlayError,
  clearOverlay,
  make,
  $$default as default,
}
/* default Not a pure module */
