// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as BojBridge from "./BojBridge.res.js";
import * as Nodepath from "node:path";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as RescriptConfig from "./RescriptConfig.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as RescriptCompiler from "./RescriptCompiler.res.js";

function log(level, prefix, msg) {
  if (level !== "silent") {
    console.log(`[rescript-vite] ` + prefix + ` ` + msg);
    return;
  }
}

function logInfo(level, msg) {
  log(level, "\x1b[36mi\x1b[0m", msg);
}

function logOk(level, msg) {
  log(level, "\x1b[32m+\x1b[0m", msg);
}

function logWarn(level, msg) {
  log(level, "\x1b[33m!\x1b[0m", msg);
}

function logErr(level, msg) {
  log(level, "\x1b[31mx\x1b[0m", msg);
}

function isDeno() {
  return (typeof Deno !== "undefined");
}

function hasRewatch(root) {
  return Nodefs.existsSync(Nodepath.join(root, "node_modules", ".bin/rewatch"));
}

function sendOverlayError(server, diagnostic) {
  server.ws.send({
    type: "error",
    err: {
      message: diagnostic.message,
      stack: "",
      id: diagnostic.file,
      frame: diagnostic.file + `:` + diagnostic.line.toString() + `:` + diagnostic.column.toString(),
      plugin: "rescript-vite",
      loc: {
        file: diagnostic.file,
        line: diagnostic.line,
        column: diagnostic.column
      }
    }
  });
}

function clearOverlay(server) {
  server.ws.send({
    type: "update",
    updates: []
  });
}

let artifactIgnorePatterns = [
  "**/*.ast",
  "**/*.cmj",
  "**/*.cmi",
  "**/*.cmt",
  "**/lib/bs/**",
  "**/lib/es6/**",
  "**/lib/js/**",
  "**/lib/ocaml/**",
  "**/.merlin",
  "**/.bsb.lock"
];

let rescriptExcludePackages = [
  "@rescript/core",
  "@rescript/runtime",
  "@rescript/react",
  "rescript"
];

function tryPascalCaseResolve(source, importer, suffix) {
  if (!source.startsWith(".")) {
    return;
  }
  let dir = Nodepath.dirname(importer);
  let base = Nodepath.basename(source);
  let firstChar = base.charAt(0).toUpperCase();
  let rest = base.slice(1);
  let pascalBase = firstChar + rest;
  let candidate = Nodepath.join(dir, Nodepath.dirname(source), pascalBase + suffix);
  if (Nodefs.existsSync(candidate)) {
    return candidate;
  }
  let altSuffix = suffix === ".res.js" ? ".res.mjs" : (
      suffix === ".res.mjs" ? ".res.js" : suffix
    );
  let altCandidate = Nodepath.join(dir, Nodepath.dirname(source), pascalBase + altSuffix);
  if (Nodefs.existsSync(altCandidate)) {
    return altCandidate;
  }
  let directCandidate = Nodepath.join(dir, Nodepath.dirname(source), base + suffix);
  if (Nodefs.existsSync(directCandidate)) {
    return directCandidate;
  }
}

function make(optionsOpt) {
  let options = optionsOpt !== undefined ? Primitive_option.valFromOption(optionsOpt) : undefined;
  let opts = Stdlib_Option.getOr(options, {
    boj: undefined,
    bojEndpoint: undefined,
    useDeno: undefined,
    rescriptBin: undefined,
    compilerFlags: undefined,
    logLevel: undefined,
    suffix: undefined,
    useRewatch: undefined,
    autoOptimizeDeps: undefined,
    autoResolve: undefined,
    autoIgnoreArtifacts: undefined
  });
  let logLevel = Stdlib_Option.getOr(opts.logLevel, "info");
  let useDeno = Stdlib_Option.getOr(opts.useDeno, isDeno());
  let wantAutoOptimize = Stdlib_Option.getOr(opts.autoOptimizeDeps, true);
  let wantAutoResolve = Stdlib_Option.getOr(opts.autoResolve, true);
  let wantAutoIgnore = Stdlib_Option.getOr(opts.autoIgnoreArtifacts, true);
  let state = {
    config: undefined,
    watchHandle: undefined,
    bojBridge: undefined,
    pendingHmrFiles: [],
    lastBuildSuccess: true,
    diagnostics: [],
    rescriptConfig: RescriptConfig.defaultRescriptConfig
  };
  return {
    name: "rescript-vite",
    enforce: "pre",
    config: () => {
      let rescriptCfg = RescriptConfig.read(".");
      state.rescriptConfig = rescriptCfg;
      if (rescriptCfg.configPath !== "") {
        log(logLevel, "\x1b[36mi\x1b[0m", `Detected ` + rescriptCfg.configPath + ` (suffix: ` + rescriptCfg.suffix + `, format: ` + rescriptCfg.packageSpec.moduleFormat + `, in-source: ` + (
          rescriptCfg.packageSpec.inSource ? "true" : "false"
        ) + `)`);
      }
      if (wantAutoOptimize || wantAutoIgnore) {
        return ((function() {
          var cfg = {};

          // Auto-exclude @rescript/* from dependency pre-bundling
          if (wantAutoOptimize) {
            cfg.optimizeDeps = {
              exclude: ["@rescript/core", "@rescript/runtime", "@rescript/react", "rescript"]
            };
          }

          // Auto-ignore build artifacts in file watcher
          if (wantAutoIgnore) {
            cfg.server = cfg.server || {};
            cfg.server.watch = cfg.server.watch || {};
            cfg.server.watch.ignored = [
              "**/*.ast", "**/*.cmj", "**/*.cmi", "**/*.cmt",
              "**/lib/bs/**", "**/lib/es6/**", "**/lib/js/**",
              "**/lib/ocaml/**", "**/.merlin", "**/.bsb.lock"
            ];
          }

          // Set NINJA_ANSI_FORCED for colored compiler output
          cfg.define = cfg.define || {};

          return cfg;
        })());
      } else {
        return ({});
      }
    },
    configResolved: resolvedConfig => {
      state.config = resolvedConfig;
      let rescriptCfg = RescriptConfig.read(resolvedConfig.root);
      state.rescriptConfig = rescriptCfg;
      let s = opts.suffix;
      if (s !== undefined) {
        let init = state.rescriptConfig;
        state.rescriptConfig = {
          name: init.name,
          suffix: s,
          packageSpec: init.packageSpec,
          sources: init.sources,
          dependencies: init.dependencies,
          configPath: init.configPath
        };
      }
      log(logLevel, "\x1b[36mi\x1b[0m", `Project root: ` + resolvedConfig.root);
      log(logLevel, "\x1b[36mi\x1b[0m", `Mode: ` + resolvedConfig.command + ` (` + resolvedConfig.mode + `)`);
      log(logLevel, "\x1b[36mi\x1b[0m", `ReScript suffix: ` + state.rescriptConfig.suffix);
      if (!state.rescriptConfig.packageSpec.inSource) {
        return log(logLevel, "\x1b[36mi\x1b[0m", `Out-of-source mode: compiled output in lib/` + (
          state.rescriptConfig.packageSpec.moduleFormat === "esmodule" ? "es6" : "js"
        ) + `/`);
      }
    },
    configureServer: _server => ((process.env.NINJA_ANSI_FORCED = "1")),
    resolveId: wantAutoResolve ? async (source, importer) => {
        if (importer === undefined) {
          return;
        }
        let suffix = state.rescriptConfig.suffix;
        let resolved = tryPascalCaseResolve(source, importer, suffix);
        if (resolved !== undefined) {
          return {
            id: resolved
          };
        }
      } : undefined,
    buildStart: async () => {
      let c = state.config;
      let root = c !== undefined ? c.root : ".";
      let wantBoj = Stdlib_Option.getOr(opts.boj, false);
      if (wantBoj) {
        let bridge = BojBridge.make(Stdlib_Option.getOr(opts.bojEndpoint, BojBridge.defaultEndpoint));
        let connected = await BojBridge.probe(bridge);
        if (connected) {
          state.bojBridge = bridge;
          log(logLevel, "\x1b[32m+\x1b[0m", "BoJ ssg-mcp connected -- build orchestration delegated");
        } else {
          log(logLevel, "\x1b[33m!\x1b[0m", "BoJ not available -- falling back to direct compiler");
        }
      }
      let useRewatch = Stdlib_Option.getOr(opts.useRewatch, hasRewatch(root));
      let init = RescriptCompiler.defaultConfig(root);
      let compilerConfig_cwd = init.cwd;
      let compilerConfig_rescriptBin = opts.rescriptBin;
      let compilerConfig_compilerFlags = Stdlib_Option.getOr(opts.compilerFlags, []);
      let compilerConfig_onDiagnostic = d => {
        state.diagnostics.push(d);
        let match = d.severity;
        let sevStr;
        sevStr = match === "Error" ? "error" : "warning";
        if (sevStr === "error") {
          log(logLevel, "\x1b[31mx\x1b[0m", d.file + `:` + d.line.toString() + ` -- ` + d.message);
          state.lastBuildSuccess = false;
          return;
        } else if (logLevel === "verbose") {
          return log(logLevel, "\x1b[33m!\x1b[0m", d.file + `:` + d.line.toString() + ` -- ` + d.message);
        } else {
          return;
        }
      };
      let compilerConfig_onFileChanged = file => {
        state.pendingHmrFiles.push(file);
      };
      let compilerConfig = {
        cwd: compilerConfig_cwd,
        rescriptBin: compilerConfig_rescriptBin,
        useDeno: useDeno,
        useRewatch: useRewatch,
        compilerFlags: compilerConfig_compilerFlags,
        onDiagnostic: compilerConfig_onDiagnostic,
        onFileChanged: compilerConfig_onFileChanged
      };
      let c$1 = state.config;
      let config = c$1 !== undefined ? c$1 : ({
          root: ".",
          command: "build",
          mode: "production"
        });
      if (config.command === "serve") {
        log(logLevel, "\x1b[36mi\x1b[0m", useRewatch ? "Starting rewatch..." : "Starting ReScript compiler in watch mode...");
        let handle = RescriptCompiler.watch(compilerConfig);
        state.watchHandle = handle;
        return log(logLevel, "\x1b[32m+\x1b[0m", useRewatch ? "Rewatch active" : "ReScript watch mode active");
      }
      log(logLevel, "\x1b[36mi\x1b[0m", "Running ReScript build...");
      let bridge$1 = state.bojBridge;
      if (bridge$1 !== undefined) {
        let result = await BojBridge.requestBuild(bridge$1, {
          projectRoot: root,
          targets: ["client"],
          incremental: false,
          changedFiles: [],
          compilerFlags: Stdlib_Option.getOr(opts.compilerFlags, [])
        });
        if (result !== undefined) {
          state.lastBuildSuccess = result.success;
          if (result.success) {
            return log(logLevel, "\x1b[32m+\x1b[0m", `BoJ build complete (` + result.durationMs.toString() + `ms, ` + result.cacheHits.toString() + ` cache hits)`);
          } else {
            return log(logLevel, "\x1b[31mx\x1b[0m", `BoJ build failed (` + result.diagnosticCount.toString() + ` errors)`);
          }
        }
        log(logLevel, "\x1b[33m!\x1b[0m", "BoJ build request failed -- falling back to direct compiler");
        let result$1 = await RescriptCompiler.build(compilerConfig);
        state.lastBuildSuccess = result$1.success;
        if (result$1.success) {
          return log(logLevel, "\x1b[32m+\x1b[0m", `Build complete (` + result$1.durationMs.toString() + `ms)`);
        } else {
          return log(logLevel, "\x1b[31mx\x1b[0m", `Build failed (` + result$1.diagnostics.length.toString() + ` errors)`);
        }
      }
      let result$2 = await RescriptCompiler.build(compilerConfig);
      state.lastBuildSuccess = result$2.success;
      if (result$2.success) {
        return log(logLevel, "\x1b[32m+\x1b[0m", `Build complete (` + result$2.durationMs.toString() + `ms)`);
      } else {
        return log(logLevel, "\x1b[31mx\x1b[0m", `Build failed (` + result$2.diagnostics.length.toString() + ` errors)`);
      }
    },
    handleHotUpdate: ctx => {
      let file = ctx.file;
      if (!(file.endsWith(".res") || file.endsWith(".resi"))) {
        return;
      }
      log(logLevel, "\x1b[36mi\x1b[0m", `File changed: ` + file);
      let suffix = state.rescriptConfig.suffix;
      let jsFile;
      if (state.rescriptConfig.packageSpec.inSource) {
        jsFile = file.endsWith(".resi") ? file.replace(".resi", suffix) : file.replace(".res", suffix);
      } else {
        let c = state.config;
        let root = c !== undefined ? c.root : ".";
        let rel = Nodepath.relative(root, file);
        let outputPath = RescriptConfig.getOutputPath(state.rescriptConfig, rel);
        jsFile = Nodepath.resolve(root, outputPath);
      }
      let modules = ctx.server.moduleGraph.getModulesByFile(jsFile);
      if (modules !== undefined && modules.length !== 0) {
        if (state.lastBuildSuccess) {
          clearOverlay(ctx.server);
        }
        let errors = state.diagnostics.filter(d => d.severity === "Error");
        if (errors.length !== 0) {
          let err = errors[0];
          if (err !== undefined) {
            sendOverlayError(ctx.server, err);
          }
        }
        state.diagnostics = [];
        return modules;
      }
      log(logLevel, "\x1b[36mi\x1b[0m", `Full reload for ` + file + ` (not in module graph)`);
    },
    buildEnd: () => {
      let errorCount = state.diagnostics.filter(d => d.severity === "Error").length;
      let warnCount = state.diagnostics.filter(d => d.severity === "Warning").length;
      if (errorCount > 0) {
        return log(logLevel, "\x1b[31mx\x1b[0m", errorCount.toString() + ` errors, ` + warnCount.toString() + ` warnings`);
      } else if (warnCount > 0) {
        return log(logLevel, "\x1b[33m!\x1b[0m", warnCount.toString() + ` warnings`);
      } else {
        return log(logLevel, "\x1b[32m+\x1b[0m", "No issues");
      }
    },
    closeBundle: () => {
      let handle = state.watchHandle;
      if (handle !== undefined) {
        RescriptCompiler.stop(handle);
        log(logLevel, "\x1b[36mi\x1b[0m", "ReScript watch mode stopped");
      }
      let bridge = state.bojBridge;
      if (bridge !== undefined) {
        BojBridge.disconnect(bridge);
        return log(logLevel, "\x1b[36mi\x1b[0m", "BoJ disconnected");
      }
    }
  };
}

let $$default = make(Primitive_option.some(undefined));

export {
  log,
  logInfo,
  logOk,
  logWarn,
  logErr,
  isDeno,
  hasRewatch,
  sendOverlayError,
  clearOverlay,
  artifactIgnorePatterns,
  rescriptExcludePackages,
  tryPascalCaseResolve,
  make,
  $$default as default,
}
/* default Not a pure module */
